name: NoraAllibhai
favicon: null
layout_spectrum: 0.09907469875179231
typography_spectrum: 0.24126482219435275
title: Nora Allibhai
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8858093169983476
  lightness: 0.09847525227814913
  saturation: 0.5670358168426901
  rhythmicContrast: 0.6115290604066104
purpose: []
